# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://brandstand.ai
title: brandstand.ai
email: hello@brandstand.ai
author: brandstand.ai
description: > # "Write an awesome description for your new site here. 
  artificial intelligence powered brand marketing tools to help
  protect and insure your reputation against social trends.
copyright: 'Copyright &copy; 2018 brandstand.ai. All Rights Reserved.'
credits: 'Theme credits: <a href="https://github.com/swcool/landing-page-theme">swcool</a>, <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/
  - title: linkedin
    url: https://linkedin.com
  - title: email
    url: 
